### ISSUE TITLE
Adding more context on setting up yarn + node js etc

### ISSUE THREAD

**Issue by moonchangin** [diyahir/GeneEmbWebApp#1]
Hi @diyahir 

Can I contribute to README.md to add more instruction on installation for yarn, node js, and python modules, so future people who are using this repository can follow along easily?

Thanks!
James

**Comment by diyahir** [comment]
I’m currently making changes that may impact installation instructions, so let's hold off on that for this week. But you can definitely contribute to the git repo when it’s in a more stable stage.

I’m currently hosting the site here: 

http://aws2.zhang-lab.org:5000/ <http://aws2.zhang-lab.org:5000/>

For if you don’t want to run locally!

**Comment by moonchangin** [comment]
Sounds good! Let see if we can create a readme.md based on the host site
